### ISSUE TITLE
how to copy on mac?

### ISSUE THREAD

**Issue by daurenswrld** [KVXYMatt/class-extractor#11]
we dont have alt?

**Comment by KVXYMatt** [comment]
You can pick whichever hotkey you want, I just use the example provided. The command you're looking for in the palette is "Extract CSS classes from HTML" and if you click the cog icon VS Code lets you add whichever keybinding you like.

![image](https://user-images.githubusercontent.com/6285184/128672744-c4e6f669-040b-42f9-baad-39db96b6597a.png)
