### ISSUE TITLE
Some troubles with SCSS extraction.

### ISSUE THREAD

**Issue by Muxailo** [KVXYMatt/class-extractor#8]
SCSS have some wrong extraction mechanism, example:
I have HTML code:

>     <div class="about">
>         <div class="about__body">
>             <div class="about__header">
>                 <div class="about__title title">ABOUT
>                     <div class="about__title subtitle">TEXT</div>
>                 </div>
>                 <div class="about__row">
>                         <div class="about__column">
>                             <div class="item-about">
>                                 <div class="item-about__icon"><img src="URL IMG" alt="" srcset=""></div>
>                                 <div class="item-about__title">TITLE NAME</div>
>                                 <div class="item-about__text">TEXT</div>
>                              </div>
>                         </div>
>                 </div>                
>             </div>
>         </div>
>     </div>
> </body>

When SCSS extract:
`.about{&__body{}&__header{}&__title{}&__text{}&__row{}&__column{}}.title{}.subtitle{}.item-about{&__icon{}.title{}&__text{}}`

How it look in separate lines (can we have this as an option instead of all code in one line?):
```
.about{
    &__body{}
    &__header{}
    &__title{}
    &__text{}
    &__row{}
    &__column{}
}

.item-about{
    &__icon{}
    &__title{}
    &__text{}
}

.title{}

.subtitle{}

.item-about{
    &__icon{}
.title{}  <-- this is wrong
    &__text{}
}
```
As you can see, because i had `.title` before, it create another  `.title` instead of `&__title`. 
Same goes for any line if it have more than 1 class.
CSS example from same HTML:

> .about { }
> .about__body { }
> .about__header { }
> .about__title { }
> .title { }
> .subtitle { }
> .about__text { }
> .about__row { }
> .about__column { }
> .item-about { }
> .item-about__icon { }
> .item-about__title { }
> .item-about__text { }

**Comment by KVXYMatt** [comment]
I agree, this is definitely an issue as is the formatting. Will have a look into this as soon as I can. Looks like a good bit of test markup as well!

**Comment by KVXYMatt** [comment]
I have rewritten the BEM indenting to something a little more rigid, release in 1.1.0 which has just been published. Having tested your example it seems to function as expected now. Sorry for the delay on fixing this, let me know if there's any issues remaining!
